running:
  port: 3002
  
redis:
  addr: localhost:6379
  password: "123456"

mysql:
  dsn: root:123456@tcp(localhost:3306)/app?parseTime=true&loc=Local&charset=utf8mb4&loc=Asia%2FShanghai
  
kafka:
  brokers:
    - localhost:9092
  topic: doc-ops

Auth:
  path: http://localhost:3001